/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdlib.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
// Bit band alias calculation in ARM:
// alias_addr = alias_base+(32*(bit_band_addr - bit_band_base))+bit*4

#define SRAM_ALIAS_BASE 0x22000000
#define SRAM_BITBAND_BASE 0x20000000

#define GET_BIT_ALIAS(BBADR, BITPOS) (uint8_t *)(SRAM_ALIAS_BASE+(32*((int)BBADR - SRAM_BITBAND_BASE)) + BITPOS *4)

#define SET_BIT_BY_ALIAS(BBADR, BITPOS, HIGH) *(GET_BIT_ALIAS(BBADR, BITPOS))=HIGH


int main(void)
{
	uint32_t *v1 = 0x20001000;//&val1;
	uint32_t *v2 = 0x20001004;//&val2;


	*v1 = 5;
	*v2 = 8;

	__asm volatile("LDR R1, =#0X20001000");
	__asm volatile("LDR R2, =#0X20001004");
	__asm volatile ("LDR R0, [R1]");
	__asm volatile ("LDR R1, [R2]");
	__asm volatile ("ADD R0,R0,R1");
	__asm volatile ("STR R0, [R2]");

	int val = 8;
	__asm volatile ("MOV R0,%0"::"r"(val));

	// Reading/writing from special registers
	uint32_t control_reg;

	__asm volatile ("MRS %0,control":"=r"(control_reg)::);

	// Bitband operation
	uint8_t *bitPtr = (uint8_t*)(SRAM_BITBAND_BASE | 0x02); //Some address in the bitband
	*bitPtr = 0xff;

	//equivalent to a read-modify-write instruction set
	*bitPtr &= ~(1<<7);

	*bitPtr = (uint8_t*)(SRAM_BITBAND_BASE | 0x03); //Some address in the bitband
	*bitPtr = 0xff;

	uint8_t *alias = GET_BIT_ALIAS(bitPtr, 7);//BIT_BAND_ACCESS((int)(bitPtr), 7);
	*alias = 0;

	*bitPtr = (uint8_t*)(SRAM_BITBAND_BASE | 0x04); //Some address in the bitband
	*bitPtr = 0xff;

	SET_BIT_BY_ALIAS(bitPtr, 7, 0);

	for(;;);
}
